// Copyright (c) 2017 Volodymyr Syvochka
#pragma once

#include "Platform.h"

#ifndef RIO_CONFIG_ALLOCATOR_DEBUG
#define RIO_CONFIG_ALLOCATOR_DEBUG 0
#endif // RIO_CONFIG_DEBUG_ALLOC

#ifndef RIO_CONFIG_ALLOCATOR_CRT
#define RIO_CONFIG_ALLOCATOR_CRT 1
#endif // RIO_CONFIG_ALLOCATOR_CRT

#ifndef RIO_CONFIG_SPSCQUEUE_USE_MUTEX
#define RIO_CONFIG_SPSCQUEUE_USE_MUTEX 0
#endif // RIO_CONFIG_SPSCQUEUE_USE_MUTEX

#ifndef RIO_CONFIG_CRT_FILE_READER_WRITER
#define RIO_CONFIG_CRT_FILE_READER_WRITER !(RIO_PLATFORM_NACL)
#endif // RIO_CONFIG_CRT_FILE_READER_WRITER

#ifndef RIO_CONFIG_CRT_PROCESS
#define RIO_CONFIG_CRT_PROCESS !(0 \
			|| RIO_PLATFORM_EMSCRIPTEN \
			|| RIO_PLATFORM_NACL \
			|| RIO_PLATFORM_WINRT \
			|| RIO_PLATFORM_XBOXONE \
			)
#endif // RIO_CONFIG_CRT_PROCESS

#ifndef RIO_CONFIG_SEMAPHORE_PTHREAD
#define RIO_CONFIG_SEMAPHORE_PTHREAD (RIO_PLATFORM_OSX || RIO_PLATFORM_IOS)
#endif // RIO_CONFIG_SEMAPHORE_PTHREAD

#ifndef RIO_CONFIG_SUPPORTS_THREADING
#define RIO_CONFIG_SUPPORTS_THREADING !(RIO_PLATFORM_EMSCRIPTEN)
#endif // RIO_CONFIG_SUPPORTS_THREADING
// Copyright (c) 2017 Volodymyr Syvochka
